# Generated by Django 5.0.6 on 2024-06-21 17:43

import db.util
import db.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPurchaseRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(default=db.util.default_year_month, max_length=7, validators=[db.validate.validate_year_month_format], verbose_name='年月')),
                ('date', models.DateField(default=db.util.defualt_year_month_start_date, verbose_name='月初めの日付')),
                ('file', models.FileField(upload_to='', verbose_name='インポートするファイル（Excel）')),
            ],
            options={
                'verbose_name': '家計簿ファイルインポート',
                'verbose_name_plural': '家計簿ファイルインポート',
                'managed': False,
            },
        ),
    ]
